name = "space-craft-planner"
compatibility_date = "2024-09-23"

pages_build_output_dir = "client/dist"

[vars]
DISCORD_BOT_WORKER_URL = "https://sc-craft-discord-bot.sostaric-quentinjr.workers.dev"
DISCORD_CLIENT_ID = "1487753855944097834"

[[r2_buckets]]
binding = "GAME_DATA_PROD"
bucket_name = "sc-craft-game-data"

[[r2_buckets]]
binding = "GAME_DATA_DEV"
bucket_name = "sc-craft-game-data-dev"
