import { expect, test } from '@playwright/test';
import { installCommunityState } from './community-fixtures';
import { captureCommunityPanel, chooseCommunityOption } from './community-helpers';

test('Organization catalogs support direct links, keyboard navigation, history and visible providers', async ({ page, colorScheme }, testInfo) => {
  const state = await installCommunityState(page, { colorScheme });
  await page.goto('/organizations?org=TESTORG&tab=blueprints');
  const blueprintTab = page.getByRole('tab', { name: /^Blueprints/ });
  await expect(blueprintTab).toHaveAttribute('aria-selected', 'true');
  const blueprintPanel = page.getByRole('tabpanel', { name: /^Blueprints/ });
  await expect(blueprintPanel.getByRole('article')).toHaveCount(4);
  const otherRifle = blueprintPanel.getByRole('article', { name: 'Account Rifle · Other Citizen', exact: true });
  await expect(otherRifle.getByText('Other Citizen', { exact: true })).toBeVisible();
  await expect(otherRifle.getByRole('button', { name: 'Request Account Rifle from Other Citizen', exact: true })).toBeVisible();
  const ownRifle = blueprintPanel.getByRole('article', { name: 'Account Rifle · Account Citizen', exact: true });
  await expect(ownRifle.getByText('Your shared blueprint', { exact: true })).toBeVisible();
  await expect(ownRifle.getByRole('button', { name: /^Request / })).toHaveCount(0);
  await captureCommunityPanel(page, blueprintPanel, testInfo, 'organizations-blueprints');

  await blueprintTab.focus();
  await blueprintTab.press('ArrowRight');
  const resourceTab = page.getByRole('tab', { name: /^Resources/ });
  await expect(resourceTab).toBeFocused();
  await expect(resourceTab).toHaveAttribute('aria-selected', 'true');
  await expect(page).toHaveURL(/org=TESTORG.*tab=resources/);
  const resourcePanel = page.getByRole('tabpanel', { name: /^Resources/ });
  await expect(resourcePanel.getByRole('article', { name: 'Iron · Other Citizen', exact: true })).toBeVisible();
  await expect(resourcePanel.getByRole('article', { name: 'Iron · Quiet Miner', exact: true })).toBeVisible();
  await captureCommunityPanel(page, resourcePanel, testInfo, 'organizations-resources');
  await resourceTab.focus();
  await resourceTab.press('End');
  const membersTab = page.getByRole('tab', { name: /^Contributors/ });
  await expect(membersTab).toBeFocused();
  await expect(page).toHaveURL(/tab=members/);
  await captureCommunityPanel(page, page.getByRole('tabpanel', { name: /^Contributors/ }), testInfo, 'organizations-contributors');
  await page.reload();
  await expect(membersTab).toHaveAttribute('aria-selected', 'true');
  await blueprintTab.click();
  await page.goBack();
  await expect(membersTab).toHaveAttribute('aria-selected', 'true');
  await page.goForward();
  await expect(blueprintTab).toHaveAttribute('aria-selected', 'true');
  await membersTab.focus();
  await membersTab.press('Home');
  await expect(blueprintTab).toBeFocused();
  await page.getByRole('button', { name: 'All organizations', exact: true }).click();
  await expect(page).toHaveURL(/\/organizations$/);
  const directorySearch = page.getByRole('searchbox', { name: 'Search organizations', exact: true });
  await directorySearch.fill('unknown-organization');
  await expect(page.getByText('No matching organizations', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Clear search', exact: true }).click();
  await expect(page.getByRole('article', { name: 'Test Organization', exact: true })).toBeVisible();
  await captureCommunityPanel(page, page.getByRole('main'), testInfo, 'organizations-directory');
  await page.getByRole('button', { name: 'Browse offers in Test Organization', exact: true }).click();
  await expect(blueprintTab).toHaveAttribute('aria-selected', 'true');
  expect(state.errors).toEqual([]);
  expect(state.unexpectedApiCalls).toEqual([]);
});

test('Organization craft targets the chosen provider, preserves resource intent and prevents another pending request', async ({ page, colorScheme }, testInfo) => {
  const state = await installCommunityState(page, { colorScheme });
  await page.goto('/organizations?org=TESTORG&tab=blueprints');
  const card = page.getByRole('article', { name: 'Account Rifle · Other Citizen', exact: true });
  await card.getByRole('button', { name: 'Request Account Rifle from Other Citizen', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Request a craft', exact: true });
  const comment = dialog.getByRole('textbox', { name: 'Comment (optional)', exact: true });
  await expect(comment).toHaveAttribute('maxlength', '1000');
  await comment.fill('For our next organization expedition.');
  await chooseCommunityOption(page, dialog.getByRole('button', { name: 'Resources', exact: true }), 'I will buy the resources');
  const dialogPath = testInfo.outputPath('organizations-craft-dialog.png');
  await dialog.screenshot({ path: dialogPath, animations: 'disabled', scale: 'css' });
  await testInfo.attach('Organization craft request', { path: dialogPath, contentType: 'image/png' });
  await dialog.getByRole('button', { name: 'Send request', exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(card.getByRole('button', { name: 'Request pending', exact: true })).toBeDisabled();
  await expect.poll(() => state.getAccount().outgoingCraftRequests.find(request => request.id.startsWith('created-'))).toMatchObject({ source: 'organization', organizationSid: 'TESTORG', blueprintId: 'account-rifle',
    ownerRsiHandle: 'OtherCitizen', comment: 'For our next organization expedition.', resourcesOption: 'buy_resources', status: 'pending' });
  expect(state.writes.filter(entry => entry.path.endsWith('/TESTORG/craft-requests'))).toHaveLength(1);
  await card.getByRole('button', { name: 'Follow my request', exact: true }).click();
  await expect(page).toHaveURL(/account\?section=requests/);
  expect(state.errors).toEqual([]);
  expect(state.unexpectedApiCalls).toEqual([]);
});

test('Organization resources remain available after a blueprint error and the failed catalog can retry', async ({ page, colorScheme }) => {
  const state = await installCommunityState(page, { colorScheme, blueprintFailures: Number.POSITIVE_INFINITY });
  await page.goto('/organizations?org=TESTORG&tab=blueprints');
  await expect(page.getByText('This catalog could not be loaded', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: /^Resources/ }).click();
  await expect(page.getByRole('article', { name: 'Iron · Other Citizen', exact: true })).toBeVisible();
  await expect(page.getByRole('article', { name: 'Iron · Quiet Miner', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: /^Blueprints/ }).click();
  const blueprintReads = state.reads.filter(entry => entry.path.endsWith('/shared-blueprints')).length;
  const resourceReads = state.reads.filter(entry => entry.path.endsWith('/shared-resources')).length;
  state.recoverBlueprintCatalog();
  await page.getByRole('button', { name: 'Try again', exact: true }).click();
  await expect(page.getByRole('article', { name: 'Account Rifle · Other Citizen', exact: true })).toBeVisible();
  expect(state.reads.filter(entry => entry.path.endsWith('/shared-blueprints'))).toHaveLength(blueprintReads + 1);
  expect(state.reads.filter(entry => entry.path.endsWith('/shared-resources'))).toHaveLength(resourceReads);
  expect(state.errors).toEqual([]);
  expect(state.unexpectedApiCalls).toEqual([]);
});

test('Organization search, contributor and quality filters reset without losing individual lots', async ({ page, colorScheme }) => {
  const state = await installCommunityState(page, { colorScheme });
  await page.goto('/organizations?org=TESTORG&tab=blueprints');
  let panel = page.getByRole('tabpanel', { name: /^Blueprints/ });
  const search = panel.getByRole('searchbox', { name: 'Search offers', exact: true });
  await search.fill('nothing-matches-community');
  await expect(panel.getByText('No matching offers', { exact: true })).toBeVisible();
  await panel.getByRole('button', { name: 'Clear filters', exact: true }).first().click();
  await expect(search).toHaveValue('');
  await chooseCommunityOption(page, panel.getByRole('button', { name: 'Contributor', exact: true }), 'Other Citizen (@OtherCitizen)');
  await expect(panel.getByRole('article')).toHaveCount(2);
  await expect(panel.getByRole('article', { name: 'Account Rifle · Account Citizen', exact: true })).toHaveCount(0);
  await panel.getByRole('button', { name: 'Clear filters', exact: true }).first().click();
  await page.getByRole('tab', { name: /^Resources/ }).click();
  panel = page.getByRole('tabpanel', { name: /^Resources/ });
  await expect(panel.getByRole('article')).toHaveCount(2);
  await chooseCommunityOption(page, panel.getByRole('button', { name: 'Sort offers', exact: true }), 'Highest quality first');
  await expect(panel.getByRole('article').first()).toHaveAttribute('aria-label', 'Iron · Other Citizen');
  await chooseCommunityOption(page, panel.getByRole('button', { name: 'Quality', exact: true }), 'Unspecified quality');
  await expect(panel.getByText('No matching offers', { exact: true })).toBeVisible();
  await panel.getByRole('button', { name: 'Clear filters', exact: true }).first().click();
  await expect(panel.getByRole('article')).toHaveCount(2);
  expect(state.errors).toEqual([]);
  expect(state.unexpectedApiCalls).toEqual([]);
});
