name = "sc-craft-discord-bot"
main = "src/index.mjs"
compatibility_date = "2026-03-29"
workers_dev = true
account_id = "ff83160753146e63dbd55a4102d48f7c"

[vars]
APP_BASE_URL = "https://itemfab.space"

[[r2_buckets]]
binding = "GAME_DATA"
bucket_name = "sc-craft-game-data"
preview_bucket_name = "sc-craft-game-data-dev"

[[r2_buckets]]
binding = "GAME_DATA_DEV"
bucket_name = "sc-craft-game-data-dev"
preview_bucket_name = "sc-craft-game-data-dev"
